travis:
  secure:
    BINSTAR_TOKEN: FO0O6LKmg0qqV4nkkSgZwGviXhVTTSzZBL+n2Tsxi7dF1t6VyZd3OBGf0KfjJB2KWml8bqH9rKNFRwrcX+GZwN7mdsoXlL9RnaA1fuqsPWv/TKAhKLXhlYegIqLtSbOppIfS2TovDnnLz4sTmRD9gZtOE1njgC9p3IIzwv6RHP+B//RKUkBylQ6yM5Ghnk3r27ecyctD+ds3iXckY5pvaOA/ZHUHl7L5m4F/QASlzUABnszXMsNM/URdChBHjYNMnlAhvT2idvmk0nRbJgmQPizo8sKNsQxBurl52FVOYorLirT0cu1k4IWEajQ2vfAKkUYAiHZYlB1qEpWbNVAuLXq1uKZ+SzEQvyeBFVJYpRclTBVOSeWnIZIRdvUAA8Dbc3Ekwj+UKDvrr9uy1Ffb8yFB9zwvuXhCYWPfShefLmiRqTZsjmjm6yxBsuKUhOQMuQHKfWGcWXswKZsDsI34tBrpilS5T47L3Ve0reD6Wkl3BPDVFYoKAMFzTi/RV2vZ8Vu9g8Im+GJhrfIgAf5Ep0k1tCJ9mEpbn6b6/nWXRLqAQsfzKvyHbV9LLD9utle6ZWlQz7BRMXiui6g7WUzdBFLQv8qd7Gw245CR31Y4Tgr4p2gTeRg3cUpaXwjh5zSReDxxS8mnibihETcb9+PHiC1ncaiYageavqBjYiAhrhA=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
